import path from '../util/path';

// {
//   iso2: "SH",
//   iso3: "SHN",
//   name: "Ascencion Island",
//   currency: "USD",
//   available: true
// },

const countries = [
    {
        iso2: 'AF',
        iso3: 'AFG',
        name: 'Afghanistan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AL',
        iso3: 'ALB',
        name: 'Albania',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'DZ',
        iso3: 'DZA',
        name: 'Algeria',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AS',
        iso3: 'ASM',
        name: 'American Samoa',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AD',
        iso3: 'AND',
        name: 'Andorra',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AO',
        iso3: 'AGO',
        name: 'Angola',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AI',
        iso3: 'AIA',
        name: 'Anguilla',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AG',
        iso3: 'ATG',
        name: 'Antigua and Barbuda',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AR',
        iso3: 'ARG',
        name: 'Argentina',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AM',
        iso3: 'ARM',
        name: 'Armenia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AW',
        iso3: 'ABW',
        name: 'Aruba',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AU',
        iso3: 'AUS',
        name: 'Australia',
        currency: 'AUD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'AT',
        iso3: 'AUT',
        name: 'Austria',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AZ',
        iso3: 'AZE',
        name: 'Azerbaijan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'BS',
        iso3: 'BHS',
        name: 'Bahamas',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BH',
        iso3: 'BHR',
        name: 'Bahrain',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BD',
        iso3: 'BGD',
        name: 'Bangladesh',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BB',
        iso3: 'BRB',
        name: 'Barbados',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BY',
        iso3: 'BLR',
        name: 'Belarus',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'BE',
        iso3: 'BEL',
        name: 'Belgium',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'BZ',
        iso3: 'BLZ',
        name: 'Belize',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BJ',
        iso3: 'BEN',
        name: 'Benin',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BM',
        iso3: 'BMU',
        name: 'Bermuda',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BT',
        iso3: 'BTN',
        name: 'Bhutan',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BO',
        iso3: 'BOL',
        name: 'Bolivia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BQ',
        iso3: 'BES',
        name: 'Bonaire, Sint Eustatius and Saba',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'BA',
        iso3: 'BIH',
        name: 'Bosnia and Herzegovina',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'BW',
        iso3: 'BWA',
        name: 'Botswana',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BV',
        iso3: 'BVT',
        name: 'Bouvet Island',
        currency: 'NOK',
        available: false,
        symbol: 'kr',
    },
    {
        iso2: 'BR',
        iso3: 'BRA',
        name: 'Brazil',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'IO',
        iso3: 'IOT',
        name: 'British Indian Ocean Territory',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'BN',
        iso3: 'BRN',
        name: 'Brunei Darussalam',
        currency: 'SGD',
        available: true,
        symbol: 'S$',
    },
    {
        iso2: 'BG',
        iso3: 'BGR',
        name: 'Bulgaria',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'BF',
        iso3: 'BFA',
        name: 'Burkina Faso',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BI',
        iso3: 'BDI',
        name: 'Burundi',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KH',
        iso3: 'KHM',
        name: 'Cambodia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CM',
        iso3: 'CMR',
        name: 'Cameroon',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CA',
        iso3: 'CAN',
        name: 'Canada',
        currency: 'CAD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CV',
        iso3: 'CPV',
        name: 'Cape Verde',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KY',
        iso3: 'CYM',
        name: 'Cayman Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CF',
        iso3: 'CAF',
        name: 'Central African Republic',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TD',
        iso3: 'TCD',
        name: 'Chad',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CL',
        iso3: 'CHL',
        name: 'Chile',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CN',
        iso3: 'CHN',
        name: 'China',
        currency: 'CNY',
        available: true,
        symbol: '--NA--',
    },
    {
        iso2: 'CX',
        iso3: 'CXR',
        name: 'Christmas Island',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CC',
        iso3: 'CCK',
        name: 'Cocos (Keeling) Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CO',
        iso3: 'COL',
        name: 'Colombia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KM',
        iso3: 'COM',
        name: 'Comoros',
        currency: 'KMF',
        available: false,
        symbol: 'CF',
    },
    {
        iso2: 'CG',
        iso3: 'COG',
        name: 'Congo',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CD',
        iso3: 'COD',
        name: 'Congo, Dem Rep Of',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CK',
        iso3: 'COK',
        name: 'Cook Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'CR',
        iso3: 'CRI',
        name: 'Costa Rica',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'HR',
        iso3: 'HRV',
        name: 'Croatia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'CU',
        iso3: 'CUB',
        name: 'Cuba',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'CW',
        iso3: 'CUW',
        name: 'Curaçao',
        currency: 'ANG',
        available: false,
        symbol: 'NAƒ',
    },
    {
        iso2: 'CY',
        iso3: 'CYP',
        name: 'Cyprus',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'CZ',
        iso3: 'CZE',
        name: 'Czech Republic',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'DK',
        iso3: 'DNK',
        name: 'Denmark',
        currency: 'DKK',
        available: true,
        symbol: 'kr.',
    },
    {
        iso2: 'DJ',
        iso3: 'DJI',
        name: 'Djibouti',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'DM',
        iso3: 'DMA',
        name: 'Dominica',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'DO',
        iso3: 'DOM',
        name: 'Dominican Republic',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TL',
        iso3: 'TLS',
        name: 'East Timor',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'EC',
        iso3: 'ECU',
        name: 'Ecuador',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'EG',
        iso3: 'EGY',
        name: 'Egypt',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SV',
        iso3: 'SLV',
        name: 'El Salvador',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GQ',
        iso3: 'GNQ',
        name: 'Equatorial Guinea',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ER',
        iso3: 'ERI',
        name: 'Eritrea',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'EE',
        iso3: 'EST',
        name: 'Estonia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'ET',
        iso3: 'ETH',
        name: 'Ethiopia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'FK',
        iso3: 'FLK',
        name: 'Falkland Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'FO',
        iso3: 'FRO',
        name: 'Faroe islands',
        currency: 'DKK',
        available: true,
        symbol: 'kr.',
    },
    {
        iso2: 'FJ',
        iso3: 'FJI',
        name: 'Fiji',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'FI',
        iso3: 'FIN',
        name: 'Finland',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'FR',
        iso3: 'FRA',
        name: 'France',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'GF',
        iso3: 'GUF',
        name: 'French Guiana',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PF',
        iso3: 'PYF',
        name: 'French Polynesia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TF',
        iso3: 'ATF',
        name: 'French Southern Territories',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'GA',
        iso3: 'GAB',
        name: 'Gabon',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GM',
        iso3: 'GMB',
        name: 'Gambia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GE',
        iso3: 'GEO',
        name: 'Georgia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'DE',
        iso3: 'DEU',
        name: 'Germany',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'GH',
        iso3: 'GHA',
        name: 'Ghana',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GI',
        iso3: 'GIB',
        name: 'Gibraltar',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'GR',
        iso3: 'GRC',
        name: 'Greece',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'GL',
        iso3: 'GRL',
        name: 'Greenland',
        currency: 'DKK',
        available: true,
        symbol: 'kr.',
    },
    {
        iso2: 'GD',
        iso3: 'GRD',
        name: 'Grenada',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GP',
        iso3: 'GLP',
        name: 'Guadeloupe',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'GU',
        iso3: 'GUM',
        name: 'Guam',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GT',
        iso3: 'GTM',
        name: 'Guatemala',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GG',
        iso3: 'GGY',
        name: 'Guernsey',
        currency: 'GGP',
        available: false,
        symbol: '£',
    },
    {
        iso2: 'GN',
        iso3: 'GIN',
        name: 'Guinea',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GW',
        iso3: 'GNB',
        name: 'Guinea-Bissau',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GY',
        iso3: 'GUY',
        name: 'Guyana',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'HT',
        iso3: 'HTI',
        name: 'Haiti',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'HM',
        iso3: 'HMD',
        name: 'Heard Island and McDonald Islands',
        currency: 'AUD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'VA',
        iso3: 'VAT',
        name: 'Holy See [Vatican City State]',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'HN',
        iso3: 'HND',
        name: 'Honduras',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'HK',
        iso3: 'HKG',
        name: 'Hong Kong',
        currency: 'HKD',
        available: true,
        symbol: 'HK$',
    },
    {
        iso2: 'HU',
        iso3: 'HUN',
        name: 'Hungary',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'IS',
        iso3: 'ISL',
        name: 'Iceland',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'IN',
        iso3: 'IND',
        name: 'India',
        currency: 'INR',
        available: true,
        symbol: '--NA--',
    },
    {
        iso2: 'ID',
        iso3: 'IDN',
        name: 'Indonesia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'IR',
        iso3: 'IRN',
        name: 'Iran',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'IQ',
        iso3: 'IRQ',
        name: 'Iraq',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'IE',
        iso3: 'IRL',
        name: 'Ireland',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'IM',
        iso3: 'IMN',
        name: 'Isle of Man',
        currency: 'GBP',
        available: false,
        symbol: '£',
    },
    {
        iso2: 'IL',
        iso3: 'ISR',
        name: 'Israel',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'IT',
        iso3: 'ITA',
        name: 'Italy',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'CI',
        iso3: 'CIV',
        name: 'Ivory Coast',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'JM',
        iso3: 'JAM',
        name: 'Jamaica',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'JP',
        iso3: 'JPN',
        name: 'Japan',
        currency: 'JPY',
        available: true,
        symbol: '¥',
    },
    {
        iso2: 'JE',
        iso3: 'JEY',
        name: 'Jersey',
        currency: 'GBP',
        available: false,
        symbol: '£',
    },
    {
        iso2: 'JO',
        iso3: 'JOR',
        name: 'Jordan',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KZ',
        iso3: 'KAZ',
        name: 'Kazakhstan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'KE',
        iso3: 'KEN',
        name: 'Kenya',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KI',
        iso3: 'KIR',
        name: 'Kiribati',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'XK',
        iso3: 'XKX',
        name: 'Kosovo',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'KW',
        iso3: 'KWT',
        name: 'Kuwait',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KG',
        iso3: 'KGZ',
        name: 'Kyrgyzstan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'LA',
        iso3: 'LAO',
        name: 'Laos',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LV',
        iso3: 'LVA',
        name: 'Latvia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'LB',
        iso3: 'LBN',
        name: 'Lebanon',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LS',
        iso3: 'LSO',
        name: 'Lesotho',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LR',
        iso3: 'LBR',
        name: 'Liberia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LY',
        iso3: 'LBY',
        name: 'Libya',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LI',
        iso3: 'LIE',
        name: 'Liechtenstein',
        currency: 'CHF',
        available: true,
        symbol: 'SFr.',
    },
    {
        iso2: 'LT',
        iso3: 'LTU',
        name: 'Lithuania',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'LU',
        iso3: 'LUX',
        name: 'Luxembourg',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MO',
        iso3: 'MAC',
        name: 'Macao',
        currency: 'HKD',
        available: true,
        symbol: 'HK$',
    },
    {
        iso2: 'MK',
        iso3: 'MKD',
        name: 'Macedonia, FYR',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MG',
        iso3: 'MDG',
        name: 'Madagascar',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MW',
        iso3: 'MWI',
        name: 'Malawi',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MY',
        iso3: 'MYS',
        name: 'Malaysia',
        currency: 'MYR',
        available: true,
        symbol: 'RM',
    },
    {
        iso2: 'MV',
        iso3: 'MDV',
        name: 'Maldives',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ML',
        iso3: 'MLI',
        name: 'Mali',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MT',
        iso3: 'MLT',
        name: 'Malta',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MH',
        iso3: 'MHL',
        name: 'Marshall Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MQ',
        iso3: 'MTQ',
        name: 'Martinique',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MR',
        iso3: 'MRT',
        name: 'Mauritania',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MU',
        iso3: 'MUS',
        name: 'Mauritius',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'YT',
        iso3: 'MYT',
        name: 'Mayotte',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'MX',
        iso3: 'MEX',
        name: 'Mexico',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'FM',
        iso3: 'FSM',
        name: 'Micronesia, Fed States of',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MD',
        iso3: 'MDA',
        name: 'Moldova',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MC',
        iso3: 'MCO',
        name: 'Monaco',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MN',
        iso3: 'MNG',
        name: 'Mongolia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ME',
        iso3: 'MNE',
        name: 'Montenegro',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'MS',
        iso3: 'MSR',
        name: 'Montserrat',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MA',
        iso3: 'MAR',
        name: 'Morocco',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MZ',
        iso3: 'MOZ',
        name: 'Mozambique',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MM',
        iso3: 'MMR',
        name: 'Myanmar',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NA',
        iso3: 'NAM',
        name: 'Namibia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NR',
        iso3: 'NRU',
        name: 'Nauru',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NP',
        iso3: 'NPL',
        name: 'Nepal',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NL',
        iso3: 'NLD',
        name: 'Netherlands',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AN',
        iso3: 'ANT',
        name: 'Netherlands Antilles',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'NC',
        iso3: 'NCL',
        name: 'New Caledonia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NZ',
        iso3: 'NZL',
        name: 'New Zealand',
        currency: 'NZD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NI',
        iso3: 'NIC',
        name: 'Nicaragua',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NE',
        iso3: 'NER',
        name: 'Niger',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NG',
        iso3: 'NGA',
        name: 'Nigeria',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NU',
        iso3: 'NIU',
        name: 'Niue',
        currency: 'NZD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'NF',
        iso3: 'NFK',
        name: 'Norfolk Island',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KP',
        iso3: 'PRK',
        name: 'North Korea',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'MP',
        iso3: 'MNP',
        name: 'Northern Mariana Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'NO',
        iso3: 'NOR',
        name: 'Norway',
        currency: 'NOK',
        available: true,
        symbol: 'kr',
    },
    {
        iso2: 'OM',
        iso3: 'OMN',
        name: 'Oman',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PK',
        iso3: 'PAK',
        name: 'Pakistan',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PW',
        iso3: 'PLW',
        name: 'Palau',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PS',
        iso3: 'PSE',
        name: 'Palestine',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PA',
        iso3: 'PAN',
        name: 'Panama',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PG',
        iso3: 'PNG',
        name: 'Papua New Guinea',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PY',
        iso3: 'PRY',
        name: 'Paraguay',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PE',
        iso3: 'PER',
        name: 'Peru',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'PH',
        iso3: 'PHL',
        name: 'Philippines',
        currency: 'PHP',
        available: true,
        symbol: '₱',
    },
    {
        iso2: 'PN',
        iso3: 'PCN',
        name: 'Pitcairn',
        currency: 'NZD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'PL',
        iso3: 'POL',
        name: 'Poland',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'PT',
        iso3: 'PRT',
        name: 'Portugal',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'PR',
        iso3: 'PRI',
        name: 'Puerto Rico',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'QA',
        iso3: 'QAT',
        name: 'Qatar',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'RE',
        iso3: 'REU',
        name: 'Reunion',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'RO',
        iso3: 'ROU',
        name: 'Romania',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'RU',
        iso3: 'RUS',
        name: 'Russia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'RW',
        iso3: 'RWA',
        name: 'Rwanda',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'BL',
        iso3: 'BLM',
        name: 'Saint Barthélemy',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'SH',
        iso3: 'SHN',
        name: 'Saint Helena',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'KN',
        iso3: 'KNA',
        name: 'Saint Kitts and Nevis',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'LC',
        iso3: 'LCA',
        name: 'Saint Lucia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'MF',
        iso3: 'MAF',
        name: 'Saint Martin (French part)',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'PM',
        iso3: 'SPM',
        name: 'Saint Pierre and Miquelon',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'VC',
        iso3: 'VCT',
        name: 'Saint Vincent and the Grenadines',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'WS',
        iso3: 'WSM',
        name: 'Samoa',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SM',
        iso3: 'SMR',
        name: 'San Marino',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'ST',
        iso3: 'STP',
        name: 'Sao Tome and Principe',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SA',
        iso3: 'SAU',
        name: 'Saudi Arabia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SN',
        iso3: 'SEN',
        name: 'Senegal',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'RS',
        iso3: 'SRB',
        name: 'Serbia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'SC',
        iso3: 'SYC',
        name: 'Seychelles',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SL',
        iso3: 'SLE',
        name: 'Sierra Leone',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SG',
        iso3: 'SGP',
        name: 'Singapore',
        currency: 'SGD',
        available: true,
        symbol: 'S$',
    },
    {
        iso2: 'SX',
        iso3: 'SXM',
        name: 'Sint Maarten (Dutch part)',
        currency: 'EUR',
        available: false,
        symbol: '€',
    },
    {
        iso2: 'SK',
        iso3: 'SVK',
        name: 'Slovakia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'SI',
        iso3: 'SVN',
        name: 'Slovenia',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'SB',
        iso3: 'SLB',
        name: 'Solomon Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SO',
        iso3: 'SOM',
        name: 'Somalia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ZA',
        iso3: 'ZAF',
        name: 'South Africa',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GS',
        iso3: 'SGS',
        name: 'South Georgia and the South Sandwich Islands',
        currency: 'FKP',
        available: false,
        symbol: 'FK£',
    },
    {
        iso2: 'KR',
        iso3: 'KOR',
        name: 'South Korea',
        currency: 'KRW',
        available: true,
        symbol: '₩',
    },
    {
        iso2: 'SS',
        iso3: 'SSD',
        name: 'South Sudan',
        currency: 'SSP',
        available: false,
        symbol: 'SSP',
    },
    {
        iso2: 'ES',
        iso3: 'ESP',
        name: 'Spain',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'LK',
        iso3: 'LKA',
        name: 'Sri Lanka',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SD',
        iso3: 'SDN',
        name: 'Sudan',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'SR',
        iso3: 'SUR',
        name: 'Suriname',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SJ',
        iso3: 'SJM',
        name: 'Svalbard and Jan Mayen',
        currency: 'NOK',
        available: false,
        symbol: 'kr',
    },
    {
        iso2: 'SZ',
        iso3: 'SWZ',
        name: 'Swaziland',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'SE',
        iso3: 'SWE',
        name: 'Sweden',
        currency: 'SEK',
        available: true,
        symbol: 'kr',
    },
    {
        iso2: 'CH',
        iso3: 'CHE',
        name: 'Switzerland',
        currency: 'CHF',
        available: true,
        symbol: 'SFr.',
    },
    {
        iso2: 'SY',
        iso3: 'SYR',
        name: 'Syria',
        currency: 'USD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'TW',
        iso3: 'TWN',
        name: 'Taiwan',
        currency: 'TWD',
        available: true,
        symbol: 'NT$',
    },
    {
        iso2: 'TJ',
        iso3: 'TJK',
        name: 'Tajikistan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'TZ',
        iso3: 'TZA',
        name: 'Tanzania',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TH',
        iso3: 'THA',
        name: 'Thailand',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TG',
        iso3: 'TGO',
        name: 'Togo',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TK',
        iso3: 'TKL',
        name: 'Tokelau',
        currency: 'NZD',
        available: false,
        symbol: '$',
    },
    {
        iso2: 'TO',
        iso3: 'TON',
        name: 'Tonga',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TT',
        iso3: 'TTO',
        name: 'Trinidad and Tobago',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TN',
        iso3: 'TUN',
        name: 'Tunisia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TR',
        iso3: 'TUR',
        name: 'Turkey',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'TM',
        iso3: 'TKM',
        name: 'Turkmenistan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'TC',
        iso3: 'TCA',
        name: 'Turks and Caicos Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'TV',
        iso3: 'TUV',
        name: 'Tuvalu',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'UG',
        iso3: 'UGA',
        name: 'Uganda',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'UA',
        iso3: 'UKR',
        name: 'Ukraine',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'AE',
        iso3: 'ARE',
        name: 'United Arab Emirates',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'GB',
        iso3: 'GBR',
        name: 'United Kingdom',
        currency: 'GBP',
        available: true,
        symbol: '£',
    },
    {
        iso2: 'US',
        iso3: 'USA',
        name: 'United States',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'UY',
        iso3: 'URY',
        name: 'Uruguay',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'UM',
        iso3: 'UMI',
        name: 'US Minor Outlying Islands',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'UZ',
        iso3: 'UZB',
        name: 'Uzbekistan',
        currency: 'EUR',
        available: true,
        symbol: '€',
    },
    {
        iso2: 'VU',
        iso3: 'VUT',
        name: 'Vanuatu',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'VE',
        iso3: 'VEN',
        name: 'Venezuela',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'VN',
        iso3: 'VNM',
        name: 'Vietnam',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'VG',
        iso3: 'VGB',
        name: 'Virgin Islands, British',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'VI',
        iso3: 'VIR',
        name: 'Virgin Islands, US',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'WF',
        iso3: 'WLF',
        name: 'Wallis and Futuna',
        currency: 'XPF',
        available: false,
        symbol: 'F',
    },
    {
        iso2: 'EH',
        iso3: 'ESH',
        name: 'Western Sahara',
        currency: 'MAD',
        available: false,
        symbol: 'Dh',
    },
    {
        iso2: 'YE',
        iso3: 'YEM',
        name: 'Yemen',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ZM',
        iso3: 'ZMB',
        name: 'Zambia',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
    {
        iso2: 'ZW',
        iso3: 'ZWE',
        name: 'Zimbabwe',
        currency: 'USD',
        available: true,
        symbol: '$',
    },
];

export const convert = (countryValue, currentFormat, newFormat) =>
    path(
        [newFormat],
        countries.find(({ [currentFormat]: value }) => value === countryValue)
    );

export const isValid = (countryValue, format) =>
    countries.some(({ [format]: countryCode }) => countryValue === countryCode);

export default countries;
